version: '3'
services:
  flask:
    build: backend
    container_name: backend-flask
    environment:
      - FLASK_DEBUG=True
      - PYTHONUNBUFFERED=True
      - MONGO_ROOT_USER=${MONGO_ROOT_USER}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - PROXY_LOGIN=${PROXY_LOGIN}
      - PROXY_PASS=${PROXY_PASS}
      - PROXY_ADDR=${PROXY_ADDR}
    restart: always
    volumes:
      - ./backend:/backend
    networks:
      - mongo_network
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:5000 main:app --timeout 1200

  mongo:
    image: mongo:6.0.1
    container_name: mongoDB
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongo_network
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongoDB
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=True
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL="mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongoDB:27017/"
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    networks:
      - mongo_network
    depends_on:
      - mongo
    ports:
      - "8081:8081"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask
      - mongo
    networks:
      - mongo_network
      - api_net

volumes:
  mongodb_data_container:

networks:
  mongo_network:
    driver: bridge
  api_net:
    driver: bridge
